"""Shell completion and a man page, generated from the argument parser.

Everything here reads ``cli.build_parser()`` rather than a hand-maintained
list, so a new subcommand or flag appears in the completion and the man page
the moment it exists. A checked-in completion script would be a second place
to forget.
"""
from __future__ import annotations

import argparse
from datetime import date

from .contracts import VoxelMillError

SHELLS = ('bash', 'zsh', 'fish')


def _subparsers(parser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices
    return {}


def _summaries(parser):
    """The one-line help each subcommand was registered with.

    ``add_parser(help=...)`` records the text on the subparsers action, not as
    the child parser's ``description``, so reading ``description`` yields
    nothing and every command documents itself as "No description".
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return {choice.dest: ' '.join((choice.help or '').split())
                    for choice in action._choices_actions}
    return {}


def _options(parser):
    """Every option string on one parser, in declaration order, deduplicated."""
    seen, options = set(), []
    for action in parser._actions:
        for flag in action.option_strings:
            if flag not in seen:
                seen.add(flag)
                options.append((flag, action))
    return options


def _takes_value(action):
    return action.nargs != 0 and not isinstance(
        action, (argparse._StoreTrueAction, argparse._StoreFalseAction,
                 argparse._StoreConstAction, argparse._HelpAction,
                 argparse._VersionAction))


def _one_line(action):
    text = (action.help or '').strip().replace('\n', ' ')
    return ' '.join(text.split())


def bash_completion(parser, program='voxelmill'):
    commands = _subparsers(parser)
    lines = [f'# {program} bash completion, generated by `{program} completion bash`.',
             f'_{program}_complete() {{',
             '  local current previous command',
             '  COMPREPLY=()',
             '  current="${COMP_WORDS[COMP_CWORD]}"',
             '  previous="${COMP_WORDS[COMP_CWORD-1]}"',
             '  command=""',
             '  local index',
             '  for ((index = 1; index < COMP_CWORD; index++)); do',
             '    case "${COMP_WORDS[index]}" in',
             '      -*) ;;',
             '      *) command="${COMP_WORDS[index]}"; break ;;',
             '    esac',
             '  done',
             '  case "$previous" in',
             # A path option completes filenames; anything else falls through
             # to the option list, which is better than offering flags where a
             # value belongs.
             '    --printer|--resin|--report|--output|--contacts|--removed-contacts|'
             '--project|--scratch-dir|--output-dir|--goo|--support-preset|--process-preset)',
             '      COMPREPLY=( $(compgen -f -- "$current") ); return 0 ;;',
             '  esac',
             '  if [[ -z "$command" ]]; then',
             f'    COMPREPLY=( $(compgen -W "{" ".join(sorted(commands))}" -- "$current") )',
             '    return 0',
             '  fi',
             '  case "$command" in']
    for name in sorted(commands):
        flags = ' '.join(flag for flag, _ in _options(commands[name]))
        lines.append(f'    {name}) COMPREPLY=( $(compgen -W "{flags}" -- "$current") ) ;;')
    lines += ['  esac',
              '  if [[ ${#COMPREPLY[@]} -eq 0 ]]; then',
              '    COMPREPLY=( $(compgen -f -- "$current") )',
              '  fi',
              '  return 0',
              '}',
              f'complete -o filenames -F _{program}_complete {program}']
    return '\n'.join(lines) + '\n'


def _zsh_escape(text):
    return text.replace('\\', '\\\\').replace("'", "'\\''").replace('[', '\\[').replace(']', '\\]')


def zsh_completion(parser, program='voxelmill'):
    commands, summaries = _subparsers(parser), _summaries(parser)
    lines = [f'#compdef {program}',
             f'# Generated by `{program} completion zsh`.',
             f'_{program}() {{',
             '  local -a commands',
             '  commands=(']
    for name in sorted(commands):
        lines.append(f"    '{name}:{_zsh_escape(summaries.get(name) or name)}'")
    lines += ['  )',
              '  _arguments -C "1: :->command" "*::arg:->args"',
              '  case $state in',
              '    command) _describe -t commands "voxelmill command" commands ;;',
              '    args)',
              '      case $words[1] in']
    for name in sorted(commands):
        specs = []
        for flag, action in _options(commands[name]):
            description = _zsh_escape(_one_line(action))
            if _takes_value(action):
                specs.append(f"'{flag}=[{description}]:value:_files'")
            else:
                specs.append(f"'{flag}[{description}]'")
        joined = ' \\\n          '.join(specs) if specs else ''
        lines.append(f'        {name})')
        lines.append(f'          _arguments {joined} "*:file:_files" ;;')
    lines += ['      esac ;;',
              '  esac',
              '}',
              f'_{program} "$@"']
    return '\n'.join(lines) + '\n'


def fish_completion(parser, program='voxelmill'):
    commands, summaries = _subparsers(parser), _summaries(parser)
    lines = [f'# Generated by `{program} completion fish`.',
             f'complete -c {program} -f']
    condition = f'__fish_seen_subcommand_from {" ".join(sorted(commands))}'
    for name in sorted(commands):
        description = (summaries.get(name) or '').replace("'", "")
        lines.append(f"complete -c {program} -n 'not {condition}' -a '{name}' "
                     f"-d '{description[:70]}'")
    for name in sorted(commands):
        for flag, action in _options(commands[name]):
            if not flag.startswith('--'):
                continue
            description = _one_line(action).replace("'", '')[:70]
            value = ' -r' if _takes_value(action) else ''
            lines.append(f"complete -c {program} -n '__fish_seen_subcommand_from {name}' "
                         f"-l {flag[2:]}{value} -d '{description}'")
    return '\n'.join(lines) + '\n'


def _roff(text):
    """Escape the characters that change roff's mind about a line.

    A leading dot starts a macro. ``.goo or .ctb destination`` became
    ``macro 'goo' not defined``. ``\\&`` is a zero-width escape that keeps the
    dot as text.
    """
    text = str(text).replace('\\', '\\\\').replace('-', '\\-')
    if text.startswith('.'):
        text = '\\&' + text
    return text


DEFAULT_SUMMARY = ('prepare, support, slice and verify a single part for a masked '
                   'stereolithography printer')


def manpage(parser, program='voxelmill', version='', section=1, released=None, summary=None):
    stamp = (released or date.today()).isoformat()
    commands, summaries = _subparsers(parser), _summaries(parser)
    lines = [f'.TH {program.upper()} {section} "{stamp}" "{_roff(version or program)}" '
             f'"{_roff(program)} manual"',
             '.SH NAME',
             # The parser's description is the module's first docstring line
             # ("Command line entry point"), which names the file rather than
             # the program. A man page's NAME line is what people search.
             f'{_roff(program)} \\- {_roff(summary or DEFAULT_SUMMARY)}',
             '.SH SYNOPSIS',
             f'.B {_roff(program)}',
             '.RI [ global-options ] " " COMMAND " " [ options ] " " [ arguments ]',
             '.SH DESCRIPTION',
             'Every command resolves settings the same way: built\\-in defaults, then the',
             'printer profile, then the matching resin process, then explicit overrides.',
             'A failure prints a structured JSON error on stderr and returns nonzero.',
             'Reports are the product; geometry is withheld when validation fails unless',
             '.B \\-\\-allow\\-unresolved',
             'is given.',
             '.SH COMMANDS']
    for name in sorted(commands):
        command = commands[name]
        lines.append(f'.SS {_roff(name)}')
        lines.append(_roff(summaries.get(name) or command.description or '') or 'No description.')
        for flag, action in _options(command):
            if flag in ('-h', '--help'):
                continue
            lines.append('.TP')
            lines.append(f'.B {_roff(flag)}')
            lines.append(_roff(_one_line(action)) or 'No description.')
    lines += ['.SH EXIT STATUS',
              '.TP', '.B 0', 'The operation completed and every check that ran passed.',
              '.TP', '.B 2', 'The operation completed and a check failed.',
              '.TP', '.B 3', 'A structured error; the JSON on stderr names the code.',
              '.SH FILES',
              '.TP', '.B ~/.config/voxelmill/profiles',
              'User printer and resin profiles. See VOXELMILL_PROFILE_PATH.',
              '.SH ENVIRONMENT',
              '.TP', '.B VOXELMILL_PROFILE_PATH',
              'Colon\\-separated directories searched for profiles before the user,',
              'system and built\\-in locations.']
    return '\n'.join(lines) + '\n'


GENERATORS = {'bash': bash_completion, 'zsh': zsh_completion, 'fish': fish_completion}


def completion(shell, parser, program='voxelmill'):
    if shell not in GENERATORS:
        raise VoxelMillError('invalid_option', f'Completion is available for {SHELLS}, not {shell!r}')
    return GENERATORS[shell](parser, program)
